version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  application:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: application
    image: application
    depends_on:
      - postgres
      - redis
      - nats
      - clickhouse
    environment:
      CONFIG_PATH: ./prod.yaml
    ports:
      - "1111:1111"