env: "prod"
log_level: "debug"
application:
  port: 1111
storage:
  host: 172.18.0.4
  port: 5432
  user: postgres
  password: password
cache:
  host: localhost
  port: 6379
  ttl: 1m
broker:
  port: 8222
  host: localhost
  subject: logs
log_storage:
  port: 9000
  host: localhost